### PR TITLE
Added hello world in lisp

### PR DESCRIPTION
**Pull request by Ashiiidev**
**please help to create my first pr**

### CODE REVIEW

**Comment by reveurguy** [comment]
Hi, thanks for the effort but a program in R has already been accepted. You can remove that folder then i'll merge the PR for lisp.

**Review by reveurguy — CHANGES_REQUESTED** [review]
remove the folder for R

**Comment by Ashiiidev** [comment]
I have deleted i please merge it

**Comment by Ashiiidev** [comment]
I have removed my r file please add my lisp file now

**Comment by Ashiiidev** [comment]
Thank you!

**Comment by reveurguy** [comment]
Make sure to give the repository a star and share about it as well! You can tweet about the repository as well using the tweet badge on the Readme file.

**Pull request merged**
