### PR TITLE
add Vimscript

### PR DESCRIPTION
**Pull request by riskodwis**

### CODE REVIEW

**Comment by reveurguy** [comment]
Please correct the folder name.

**Comment by reveurguy** [comment]
Please update the branch once, pull all changes from the main repository, then I'll merge.

**Review by riskodwis — COMMENTED** [review]
.

**Review by riskodwis — COMMENTED** [review]
[Vimscript.zip](https://github.com/GDSC-SGGSCC/Hacktoberfest-22/files/9703240/Vimscript.zip)

**Pull request closed without merging**
