### PR TITLE
prolog hello world

### PR DESCRIPTION
**Pull request by Raja-s-k**
Prolog lang

### CODE REVIEW

**Review by reveurguy — CHANGES_REQUESTED** [review]
undo the Go folder changes, remove your file from the Go folder and add the Prolog folder only

**Comment by Raja-s-k** [comment]
yeah....... its done

**Comment by reveurguy** [comment]
Don't remove the existing file from the Go folder, keep that. Also update your fork with the latest changes.

**Comment by reveurguy** [comment]
Also why are there 2 files in prolog?

**Review by reveurguy — CHANGES_REQUESTED** [review]
the hello-world.pl file code doesn't prints hello world.

**Comment by Raja-s-k** [comment]
Now i think everything is fixed.........
Pls review it

**Comment by reveurguy** [comment]
@Mergifyio update

**Pull request merged**
